### ISSUE TITLE
The collection has been modified; the enumeration may not be performed.

### ISSUE THREAD

**Issue by Ray-77** [CityOfZion/neo-gui-wpf#16]
When I open the wallet file and sync,
![enum](https://user-images.githubusercontent.com/17636881/32474554-00ce40c8-c3a8-11e7-9d8d-51363f1e3fc0.png)

发生了 System.InvalidOperationException
  HResult=0x80131509
  Message=集合已修改；可能无法执行枚举操作。
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Neo.UI.Home.AssetsViewModel.GetAsset(UInt256 assetId) in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Home\AssetsViewModel.cs:line 103
   at Neo.UI.Home.HomeViewModel.UpdateAssetBalances() in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Home\HomeViewModel.cs:line 527
   at Neo.UI.Home.HomeViewModel.UpdateBalances(TimeSpan persistenceSpan) in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Home\HomeViewModel.cs:line 468
   at Neo.UI.Home.HomeViewModel.UpdateWallet(Object sender, ElapsedEventArgs e) in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Home\HomeViewModel.cs:line 442
   at System.Timers.Timer.MyTimerCallback(Object state)

**Comment by justingaffney** [comment]
This issue should be fixed now. Please let me know if it is still occurring for you
