### ISSUE TITLE
The object reference is not set to an instance of the object.

### ISSUE THREAD

**Issue by Ray-77** [CityOfZion/neo-gui-wpf#26]
When I try to transfer assets,

发生了 System.NullReferenceException
  HResult=0x80004003
  Message=未将对象引用设置到对象的实例。
  Source=neo-gui
  StackTrace:
   at Neo.UI.Base.Dialogs.InformationBox.Show(String text, String message, String title) in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Base\Dialogs\InformationBox.xaml.cs:line 20
   at Neo.UI.Base.Helpers.TransactionHelper.SignAndShowInformation(Transaction tx) in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Base\Helpers\TransactionHelper.cs:line 38
   at Neo.UI.Home.HomeViewModel.Transfer() in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Home\HomeViewModel.cs:line 772
   at Neo.UI.Base.MVVM.RelayCommand.<>c__DisplayClass5_0.<.ctor>b__0(Object parameters) in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Base\MVVM\RelayCommand.cs:line 18
   at Neo.UI.Base.MVVM.RelayCommand.Execute(Object parameter) in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Base\MVVM\RelayCommand.cs:line 35
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Neo.Program.Main() in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\Program.cs:line 41

**Comment by justingaffney** [comment]
This issue should be fixed now

**Comment by justingaffney** [comment]
Also thanks for testing the application and raising these issues, I appreciate it
