### ISSUE TITLE
SQLite Error 1: 'no such table: @p0'

### ISSUE THREAD

**Issue by Ray-77** [CityOfZion/neo-gui-wpf#31]
![2017-11-13_11-25-51](https://user-images.githubusercontent.com/17636881/32708510-748f7e66-c865-11e7-8ed3-ee16ba0e239e.png)

发生了 Microsoft.Data.Sqlite.SqliteException
  HResult=0x80004005
  Message=SQLite Error 1: 'no such table: @p0'.
  Source=<无法计算异常源>
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, FormattableString sql)
   at Neo.Implementations.Wallets.EntityFramework.UserWallet.Rebuild()
   at Neo.UI.Home.HomeViewModel.<OpenWallet>d__102.MoveNext() in C:\Users\fansh\Source\Repos\neo-gui-wpf\neo-gui\UI\Home\HomeViewModel.cs:line 702

**Comment by justingaffney** [comment]
The wallet implementation classes in the latest version of the NEO library do have any rebuild functionality, so wallet repair mode is no longer supported in the application. This error shouldn't occur anymore
