### ISSUE TITLE
An error has occurred when I opened a wallet file.

### ISSUE THREAD

**Issue by Ray-77** [CityOfZion/neo-gui-wpf#9]
发生了 System.NotSupportedException
  HResult=0x80131515
  Message=该类型的 CollectionView 不支持从调度程序线程以外的线程对其 SourceCollection 进行的更改。
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Neo.UI.Home.TransactionsViewModel.UpdateTransactions(IEnumerable`1 transactions) in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Home\TransactionsViewModel.cs:line 72
   at Neo.UI.Home.HomeViewModel.CurrentWallet_TransactionsChanged(Object sender, IEnumerable`1 transactions) in C:\Users\fansh\Source\Repos\neo-gui-wpf2\neo-gui\UI\Home\HomeViewModel.cs:line 282
   at Neo.Implementations.Wallets.EntityFramework.UserWallet.OnProcessNewBlock(Block block, IEnumerable`1 added, IEnumerable`1 changed, IEnumerable`1 deleted)
   at Neo.Wallets.Wallet.ProcessNewBlock(Block block)
   at Neo.Wallets.Wallet.ProcessBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by lukeskinner** [comment]
Translated error message (google): 
This type of CollectionView does not support changes to its SourceCollection from threads other than the scheduler thread. 

The insert into the observable collection just needs to be invoked on the UI thread.

**Comment by justingaffney** [comment]
Ok I'll make sure all ObservableCollections are updated on UI thread only

**Comment by justingaffney** [comment]
@Ray-77 the issue should be fixed now. Could you please confirm, using the latest version of the master branch, that the error no longer occurs when opening the wallet file?
